version: '3.8'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: markuser4556/kittygram_backend:latest
    env_file: .env
    restart: always
    volumes:
      - static:/app/collected_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    image: markuser4556/kittygram_frontend:latest
    env_file: .env
    restart: always
    volumes:
      - static:/static
    depends_on:
      - backend

  gateway:
    image: markuser4556/kittygram_gateway:latest
    env_file: .env
    restart: always
    ports:
      - 9000:80
    volumes:
      - static:/app/collected_static
      - media:/media
    depends_on:
      - backend
      - frontend